language: java
install: true

os: linux
dist: trusty
jdk: oraclejdk8
before_script:
  - chmod +x gradlew
script:
  - ’./gradlew clean build’
  - ’./gradlew test’
  - ./gradlew jacocoTestReport
after_success:
  - bash <(curl -s https://codecov.io/bash)